model:
  in_channels: 1
  n_layers: 3
  hidden_size: 12
  representation_size: 24
loss:
  inv_coeff: 25
  var_coeff: 15
  cov_coeff: 10
  gamma: 1
trainer:
  learning_rate: 1.0e-3
  batch_size: 128
  n_epochs: 30
  device: cuda:2
